export const ActionType = {
  ADD_BOARD: "ADD_BOARD",
  RENAME_BOARD: "RENAME_BOARD",
  REMOVE_BOARD: "REMOVE_BOARD",
  ARCHIVE_BOARD: "REMOVE_BOARD",
  TOGGLE_BOOKMARK_BOARD: "TOGGLE_BOOKMARK_BOARD",
  NOTHING: "NOTHING",
}

export const DialogType = {
  ADD_BOARD: "ADD_BOARD",
  RENAME_BOARD: "RENAME_BOARD",
  NOTHING: "NOTHING",
}