export const ActionType = {
  ADD_CARD: "ADD_CARD",
  ADD_GROUP: "ADD_GROUP",
  COPY_GROUP: "COPY_GROUP",
  MOVE_GROUP: "MOVE_GROUP",
  RENAME_GROUP: "RENAME_GROUP",
  ARCHIVE_GROUP: "ARCHIVE_GROUP",
  MOVE_ALL_CARDS: "MOVE_ALL_CARDS",
  ARCHIVE_ALL_CARDS: "ARCHIVE_ALL_CARDS",
  NOTHING: "NOTHING",
}

export const DialogType = {
  ADD_CARD: "ADD_CARD",
  ADD_GROUP: "ADD_GROUP",
  MOVE_CARD: "MOVE_CARD",
  MOVE_GROUP: "MOVE_GROUP",
  NOTHING: "NOTHING",
}